# Generated by Django 4.2.2 on 2023-08-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car_Platform", "0002_rename_make_car_car_make"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
